-- MySQL Script generated by MySQL Workbench
-- Thu Jul 25 10:44:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idClientes` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NULL,
  `Logradouro` VARCHAR(45) NULL,
  `Número` VARCHAR(45) NULL,
  `Bairro` VARCHAR(45) NULL,
  `Cidade` VARCHAR(45) NULL,
  `Telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`idClientes`),
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Tabela de clientes';


-- -----------------------------------------------------
-- Table `mydb`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produtos` (
  `idProdutos` INT NOT NULL,
  `Classe` VARCHAR(45) NULL,
  `Cor` VARCHAR(45) NULL,
  `Tamanho` VARCHAR(45) NULL,
  `Preco_custo` FLOAT NULL,
  `Preco_venda` FLOAT NULL,
  `Qtd` INT NULL,
  PRIMARY KEY (`idProdutos`))
ENGINE = InnoDB
COMMENT = 'Tabela de produtos';


-- -----------------------------------------------------
-- Table `mydb`.`Fluxo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fluxo` (
  `QtdVendas` INT NOT NULL AUTO_INCREMENT,
  `Valor_total` FLOAT NULL,
  `Lucro_liquido` FLOAT NULL,
  PRIMARY KEY (`QtdVendas`))
ENGINE = InnoDB
COMMENT = 'Fluxo de caixa';

CREATE USER 'root' IDENTIFIED BY '123PAPAYA@';

GRANT ALL ON `mydb`.* TO 'root';
GRANT SELECT ON TABLE `mydb`.* TO 'root';
GRANT SELECT, INSERT, TRIGGER ON TABLE `mydb`.* TO 'root';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `mydb`.* TO 'root';
GRANT EXECUTE ON ROUTINE `mydb`.* TO 'root';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
